branch-defaults:
  main:
    environment: cs3219-movie-api-dev
environment-defaults:
  cs3219-movie-api-dev:
    branch: null
    repository: null
global:
  application_name: cs3219-movie-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: euzintan
  repository: null
  sc: git
  workspace_type: Application
